version: '3.8'

services:
  snowlander:
    build: .
    container_name: snowlander
    ports:
      - "8000:8000"
    volumes:
      # Mount your music directory (read-only)
      - ./test_data/music:/app/data/music:ro
      # Mount database directory (persistent)
      - ./test_data/database:/app/data/database
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - MUSIC_DIR=/app/data/music
      - DATABASE_URL=sqlite+aiosqlite:///app/data/database/bot.db
      - WEB_PORT=8000
    restart: unless-stopped
